apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dguuqnk15-go-gitops
  description: This is GitOps manifest for dguuqnk15-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=dguuqnk15-go
    backstage.io/kubernetes-id: dguuqnk15-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: dguuqnk15-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:dguuqnk15-go
