apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dguuqnk15-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dguuqnk15-go 
  name: dguuqnk15-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dguuqnk15-go 
